name: PrTitleSemanticLint
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Ensure PR Title is Semantic
        run: |
          npm ci
          npx @coveo/is-pr-title-semantic
